production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
development:
  sessions:
    default:
      database: takamoriaiko_api_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: takamoriaiko_api_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
