production: 
  clients: 
    default: 
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 30
development:
  clients:
    default:
      database: takamoriaiko_api_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: takamoriaiko_api_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
